import { Header } from '@/components/Header'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark'>
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col antialiased">
          <Header />

          <section className='flex flex-1 flex-col gap-4 p-8 pt-6'>
            {children}
          </section>
        </main>
      </body>
    </html>
  )
}
